version: 2.1
orbs:
  node: circleci/node@4
  codecov: codecov/codecov@1
jobs:
  test:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: test
          command: npm run test:ci
      - run:
          name: lint
          command: npm run lint
      - codecov/upload
  release:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - release:
          filters:
            branches:
              only:
                - master
          context:
            - npm
          requires:
            - test
