name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # https://github.com/wyvox/action-setup-pnpm
      - uses: wyvox/action-setup-pnpm@d84148cd87d55adb709e92120c709b88d15bceac # v4.0.0
        with: { node-version: 24 }

      - name: lint
        run: pnpm run lint

      - name: typecheck
        run: pnpm run typecheck

      - name: test
        run: pnpm run test

      - name: build
        run: pnpm run build
